---
title: "Schedule"
output:
  html_document:
    toc: true
    toc_float: true
---

```{r, include=FALSE}
library(tidyverse)
library(readxl)
library(fontawesome)
library(gt)

knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE)


table_style <- function(data) {
  data %>%
    opt_table_lines(extent = "none") %>%
    opt_table_outline(style = "solid", width = px(3), color = "black") %>% 
    tab_options(
      heading.border.bottom.color = "black",
      heading.border.bottom.style = "solid",
      table.border.top.color = "black",
      table_body.hlines.color = "black",
      table_body.border.top.color = "black",
      table_body.border.top.style = "solid",
      table_body.border.bottom.color = "black",
      table_body.border.bottom.style = "solid",
      column_labels.border.bottom.color = "black",
      column_labels.border.bottom.style = "solid",
      column_labels.border.top.color = "black",
      column_labels.background.color = "#56B4E9",
      table.width = pct(100),
      container.width = pct(100)
    )
}

sched <- read_xlsx(here::here("nopublish", "schedule.xlsx"), sheet = "schedule") %>% 
  mutate(
    Reading = paste0(Reading, "(", reading_link, ")"),
    Slides = paste0(Slides, "(", slides_link, ")"),
    Lecture = paste0(Lecture, "(", lecture_link, ")", "<br>", "Passcode: ", lecture_passcode),
    Assigned = ifelse(str_detect(Assigned, "Homework"), Assigned,
                      paste0(Assigned, "(", assigned_link, ")")),
    Due = paste0(Due, "(", due_link, ")"),
    Date = format(as.Date(Date), "%b-%d")
    ) %>% 
  select(-ends_with("link"), -ends_with("shortcut"), -c(Topic, screenshot, lecture_passcode)) %>% 
  mutate(across(everything(), ~ifelse(. == "NA(NA)", NA_character_, .))) %>% 
  mutate(Lecture = ifelse(str_detect(Lecture, "fas"), Lecture, NA_character_)) %>% 
  mutate(across(everything(), ~str_remove(., "\\(NA\\)"))) %>% 
  nest(data = c(Date, Reading, Slides, Lecture, Assigned, Due)) 

tbl_fx <- function(n){
  sched %>% 
  slice(n) %>% 
  select(data) %>% 
  unnest(cols = c(data)) %>% 
  gt::gt() %>% 
  fmt_markdown(columns = c(Reading, Slides, Lecture, Assigned, Due)) %>% 
  fmt_missing(
    columns = everything(),
    missing_text = ""
  ) %>% 
  cols_label(
    Date = md("<i class='far fa-calendar'></i>")
  ) %>% 
  table_style()
}
```
<br>
<br>
<br>

## Week 1: Introduction

```{r}

tbl_fx(1) %>% 
  tab_footnote(
    footnote = md("This is a brief older version. For the longer, updated version, see [here](https://style.tidyverse.org/). You don’t need to read this longer version."),
    locations = cells_body(
      columns = Reading, rows = 1)
  ) %>% 
  tab_footnote(
    footnote = "I do not rearrange my RStudio panes as he does.",
    locations = cells_body(
      columns = Assigned, rows = 1)
  ) 
```
<br>
<br>
<br>

## Week 2: Workflow

<a href="C:/Users/jnese/Desktop/BRT/Teaching/Intro-Data-Science/c1-intro-fall-2021/homeworks/hw1.Rmd" download>Download link</a>

```{r}
tbl_fx(2)
```
<br>
<br>
<br>

## Week 3: `{ggplot2}`

```{r}
tbl_fx(3)
```
<br>
<br>
<br>

## Week 4: `{dplyr}`

```{r}
tbl_fx(4)
```
<br>
<br>
<br>

## Week 5: Mutating Joins

```{r}
tbl_fx(5)
```
<br>
<br>
<br>

## Week 6: RMarkdown

```{r}
tbl_fx(6)
```
<br>
<br>
<br>

## Week 7: GitHub

```{r}
tbl_fx(7)
```
<br>
<br>
<br>

## Week 8: Tidy Data

```{r}
tbl_fx(8)
```
<br>
<br>
<br>

## Week 9: Factors & Pull Request

```{r}
tbl_fx(9)
```
<br>
<br>
<br>

## Week 10: Presentations

```{r}
tbl_fx(10)
```
<br>
<br>
<br>

## Week 11: No class: Final papers due

